name: Deploy Bicep to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Decode Azure credentials and login manually
        run: |
          echo '${{ secrets.AZURE_CREDENTIALS }}' > creds.json

          # Print the keys to verify format (safe)
          echo "Credentials keys:" && jq 'keys' creds.json

          # Log in using Azure CLI
          az login --service-principal \
            --username $(jq -r .clientId creds.json) \
            --password $(jq -r .clientSecret creds.json) \
            --tenant $(jq -r .tenantId creds.json)

          # Set the correct subscription
          az account set --subscription $(jq -r .subscriptionId creds.json)

      - name: Deploy Bicep
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: assignment
          template: ./main.bicep
          parameters: adminPassword=${{ secrets.ADMIN_PASSWORD }}
